twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      joystick:
        topic   : joy_vel
        timeout : 0.5
        priority: 94
      keyboard: 
        topic   : key_vel
        timeout : 0.5
        priority: 90
      navigation:
        topic   : nav_vel
        timeout : 0.5
        priority: 96  # Set this higher than teleop priority to allow navigation to take precedence
      obstacle_avoidance:
        topic: cmd_vel_safe
        timeout: 0.5
        priority: 100